services:
  
  digidrive-postgres-doc:
    image: postgres:15
    container_name: digidrive-postgres-doc
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: digidrive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - digidrive_data:/var/lib/postgresql/data
  # postgres-auth:
  #   image: postgres:15
  #   container_name: postgres-auth
  #   environment:
  #     POSTGRES_DB: secure_road_auth
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata_auth:/var/lib/postgresql/data
  #   networks:
  #     - diginet
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     retries: 5

  # postgres-main:
    # image: postgres:15
    # container_name: postgres-main
    # environment:
    #   POSTGRES_DB: digi_drive
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5433:5432"
    # volumes:
    #   - pgdata_main:/var/lib/postgresql/data
    # networks:
    #   - diginet
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   retries: 5

  mongo:
    image: mongo:6
    container_name: digidrive-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - diginet

  redis:
    image: redis:7
    container_name: digidrive-redis
    ports:
      - "6379:6379"
    networks:
      - diginet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: digidrive-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - diginet

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: digidrive-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - diginet

volumes:
  pgdata_auth:
  pgdata_main:
  mongo_data:
  digidrive_data:

networks:
  diginet:
    driver: bridge

