server:
  port: 9001

spring:
  application:
    name: document-service

  # PostgreSQL for users, vehicles, violations
  datasource:
    url: jdbc:postgresql://localhost:5434/digidrive
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # MongoDB for documents
  data:
    mongodb:
      uri: mongodb://localhost:27017/digidrive_docs

# Eureka client registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
